#ifndef _SCRYPT_PLATFORM_H_
#define	_SCRYPT_PLATFORM_H_

#define HAVE_DECL_BE64ENC 0
#define HAVE_INTTYPES_H 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1

#endif /* !_SCRYPT_PLATFORM_H_ */
