name: Test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [25, 26, 27]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Check format
      run: rebar3 as test fmt -c
    - name: Unit tests
      run: rebar3 as test eunit
    - name: Proper tests
      run: rebar3 as test proper

  macos:
    name: Test on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Erlang and rebar3
      run: brew install erlang rebar3
    - name: Compile
      run: rebar3 compile
    - name: Check format
      run: rebar3 as test fmt -c
    - name: Unit tests
      run: rebar3 as test eunit
    - name: Proper tests
      run: rebar3 as test proper
